#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Alternative decomposeParDict name:
#decompDict="-decomposeParDict system/decomposeParDict.6"
cp -r ~/RUN/a.foam ~/RUN/cylinder

runApplication surfaceGenerateBoundingBox cylinder.stl cylinder_box.stl 96e-6 192e-6 4.8e-5 4.8e-5 96e-6 96e-6

runApplication surfaceFeatureEdges cylinder_box.stl cylinder.fms -angle 30

runApplication cartesianMesh

runApplication checkMesh

# single
#runApplication createPatch -overwrite
#restore0Dir
#runApplication renumberMesh -overwrite
#runApplication simpleFoam


# parallel
#runApplication decomposePar
#runParallel createPatch -overwrite
#restore0Dir -processor
#runParallel renumberMesh -overwrite
#runParallel $(getApplication)  #controldictのapplicationに書かれているソルバを実行
#runApplication reconstructParMesh -constant
#runApplication reconstructPar
